SET NAMES utf8mb4;

SET FOREIGN_KEY_CHECKS = 0;

-- htmlテーブルの作成
DROP TABLE IF EXISTS html;

CREATE TABLE html (
    html_no INT NOT NULL AUTO_INCREMENT COMMENT 'HTML番号',
    html_content TEXT DEFAULT NULL COMMENT '内容（from RFT）空文字OK',
    enabled TINYINT DEFAULT 1 COMMENT '論理削除フラグ',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
    PRIMARY KEY (html_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

START TRANSACTION;

COMMIT;

SET FOREIGN_KEY_CHECKS = 1; 