SET NAMES utf8mb4;

SET FOREIGN_KEY_CHECKS = 0;

-- seqテーブルの作成
DROP TABLE IF EXISTS seq;

CREATE TABLE seq (
    seq_key VARCHAR(20) NOT NULL COMMENT 'シーケンスキー',
    seq_no BIGINT DEFAULT 1 COMMENT 'シーケンス番号',
    enabled TINYINT DEFAULT 1 COMMENT '論理削除フラグ',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
    PRIMARY KEY (seq_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

START TRANSACTION;

COMMIT;

SET FOREIGN_KEY_CHECKS = 1; 