SET NAMES utf8mb4;

SET FOREIGN_KEY_CHECKS = 0;

-- admin_org_imgテーブルの作成
DROP TABLE IF EXISTS admin_org_img;

CREATE TABLE admin_org_img (
    org_no INT NOT NULL,
    img_no INT NOT NULL,
    enabled TINYINT DEFAULT 1 COMMENT '論理削除フラグ',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
    PRIMARY KEY (org_no, img_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

START TRANSACTION;



COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
